name: screen_recorder
description: Record your Flutter widgets and export the recordings as a GIF
version: 0.3.0
repository: https://github.com/ueman/screenrecorder
issue_tracker: https://github.com/ueman/screenrecorder/issues
funding:
  - https://github.com/sponsors/ueman
  - https://www.buymeacoffee.com/jonasuekoetter
topics: 
  - gif
  - recording
  - screen
  - video

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2
  path_provider: ^2.0.8
 # ffmpeg_kit_flutter_min_gpl: ^4.5.1
 ### ffmpeg_kit_flutter_full: ^4.5.1
##  flutter_ffmpeg: ^0.4.2
  ffmpeg_kit_flutter: ^6.0.3
  permission_handler: ^11.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"
